name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release --no-sound-null-safety
      - run: |
            git pull origin master
            touch empty_file_trigger
            git status
            git checkout -b gh-pages
            git add .
            git commit -m "update"
            git push origin gh-pages -
