name: HAN
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release --no-sound-null-safety
      - run: |
            cd ../build/web
            git config --global user.email absinthe4902@naver.com
            git config --global user.name leeleelee3264
            git remote set-url origin https://${{secrets.commit_secret}}@github.com/leeleelee3264/han-birthday.git
            git checkout -b gh-pages
            touch empty_file_trigger
            date >> empty_file_trigger
            git status
            git add .
            git commit -m "update"
            git push origin gh-pages -f
